// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cycles": state Resource Client
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/cycles-backend/design
// --out=$(GOPATH)/src/github.com/rchampourlier/cycles-backend
// --version=v1.3.0

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateStatePayload is the state create action payload.
type CreateStatePayload struct {
	State string `form:"state" json:"state" xml:"state"`
}

// CreateStatePath computes a request path to the create action of state.
func CreateStatePath() string {

	return fmt.Sprintf("/states/")
}

// Create a new state
func (c *Client) CreateState(ctx context.Context, path string, payload *CreateStatePayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateStateRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateStateRequest create the request corresponding to the create action endpoint of the state resource.
func (c *Client) NewCreateStateRequest(ctx context.Context, path string, payload *CreateStatePayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// ShowStatePath computes a request path to the show action of state.
func ShowStatePath() string {

	return fmt.Sprintf("/states/latest")
}

// Get latest state
func (c *Client) ShowState(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowStateRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowStateRequest create the request corresponding to the show action endpoint of the state resource.
func (c *Client) NewShowStateRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
