// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cycles": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/rchampourlier/cycles-backend/design
// --out=$(GOPATH)/src/github.com/rchampourlier/cycles-backend
// --version=v1.3.0

package app

// State of the Cycles frontend application (default view)
//
// Identifier: application/cycles.state+json; view=default
type CyclesState struct {
	// JSON state of the application
	State *string `form:"state,omitempty" json:"state,omitempty" xml:"state,omitempty"`
}
